### ISSUE TITLE
Questions about the file bytes length of ByteFormer

### ISSUE THREAD

**Issue by DanJun6737** [apple/ml-cvnets#100]
Hello!

I read the ByteFormer paper and it's really an amazing piece of work! And I read the code about the encoding of file bytes: https://github.com/apple/ml-cvnets/blob/main/data/transforms/image_bytes.py
We apply the code to our own datasets. 
However, we found that when using "png" or "jpeg" encoding mode, the file bytes length of each sample is not consistent. How to solve this problem of file bytes length change?

Thanks a lot!

**Comment by DanJun6737** [comment]
@mchorton

**Comment by mchorton** [comment]
Hi @DanJun6737,

For JPEG: Our collate functions handle variable-length samples. See here: https://github.com/apple/ml-cvnets/blob/main/data/collate_fns/byteformer_collate_functions.py

For the PNG experiments, the outputs should be the same length. The reason yours aren't is due to a bug, where compress_level was not being passed as a kwarg. As mentioned in our paper, we deactivate zlib compression in our experiments - this bit of code was missing. Note, our experimental results in the paper were not affected (the bug was introduced later, when refactoring the code).

The fix is here: https://github.com/apple/ml-cvnets/commit/fc62a84d98731764d9ef2ce284c4cdcab05fea4a . Please make sure to apply it to your experiments. You can just pull the update that I pushed to the `main` branch.

**Comment by DanJun6737** [comment]
Thank you very much for your answer.
