### ISSUE TITLE
Segmentation Head for Custom Dataset is not automatically connected!

### ISSUE THREAD

**Issue by umitkacar** [apple/ml-cvnets#29]
I like your library. Thank you for this.

I tried to train my Custom Dataset. I created CustomDataset Class. Class number of my dataset is 10. I used pretrained mobilenetv2 weights. When I run it, I have ize `mismatch for seg_head.classifier.block.conv.bias: copying a param with shape torch.Size([150]) from checkpoint, the shape in current model is torch.Size([10])`

Because class number of Ade20k Dataset is 150. Mine is 10.  I think the Segmentation head is automatically connected.
Most libraries do this automatically. How can I fix this? Are you going to post a command for fine-tuning?

**Comment by sacmehta** [comment]
Thanks for your interest in our library. Our current set-up does not support fine-tuning a segmentation model, mainly because we did not have any such use case. We will include this feature in future releases.

At this point, I think you can use either of the following options:

1. Initialize only classification backbone. See [here](https://apple.github.io/ml-cvnets/en/models/segmentation/README-segmentation-deeplabv3-tutorial.html#training-segmentation-network) for details.
2. Write a functionality to support fine-tuning segmentation network. For this part, you need to implement a `update_classifier` function (a similar function is implemented for classification tasks [here](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/cvnets/models/classification/base_cls.py#L71), which you can use as a reference) and then call this function when building the [model](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/cvnets/models/segmentation/__init__.py#L37) ( a similar functionality is implemented for classification backbones. see [here](https://github.com/apple/ml-cvnets/blob/84d992f413e52c0468f86d23196efd9dad885e6f/cvnets/models/classification/__init__.py#L82)). 

Hope this helps!

**Comment by umitkacar** [comment]
I solved it in a simpler way. I used the classification model as a backbone. I used the segmentation model with the same backbone as the config .yaml file. Thus, I can fine-tune the segmentation model. Simple thinking is always needed :) Thank you for your help.

**Comment by umitkacar** [comment]
Did you fix it? 
@sacmehta suggested  `pip install —editable .`

**Comment by nbansal90** [comment]
@umitkacar Yes! That fixed the issue for me.
