### ISSUE TITLE
Use extra coco dataset for segmentation

### ISSUE THREAD

**Issue by zhangzjn** [apple/ml-cvnets#57]
Hi, I find `use_coco_data: true` in the segmentation task, and this does not seem to be a standard test setting? Could you update the standard results for aligning with the result of [deeplabv3 in mmdet](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/deeplabv3), this would be very helpful for us to follow your works~

**Comment by sacmehta** [comment]
[Deeplabv3](https://arxiv.org/pdf/1706.05587.pdf) use models pre-trained on MS-COCO and then fine-tune on PASCAL VOC 2012. Instead of doing two stage training, we train models jointly. So, our training recipe is in alignment with the one reported in [Deeplab](https://arxiv.org/pdf/1606.00915.pdf) papers.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/18603245/198859351-9e5a7394-e217-45aa-9c55-8fcb357a3af6.png">
